### ISSUE TITLE
todoApp

### ISSUE THREAD

**Issue by ericakok** [ericakok/todoApp#1]
@codepathreview and @codepath

**Comment by codepathreview** [comment]
Hi @ericakok 

Could you pls follow the guide here - http://courses.codepath.com/courses/android_university_fast_track/pages/submitting_assignments, and upload a README and GIF for your assignment? Once you are done, pls update the status here.

Thanks

**Comment by ericakok** [comment]
Sorry about that. Done! @codepathreview @codepath
